\echo Use "CREATE EXTENSION bloomfilter (blmfl)" to load this file. \quit

CREATE TYPE BLMFL_RESULT AS (filt BYTEA, m INT, n INT, k INT, t INT); 

CREATE OR REPLACE FUNCTION blmfl_test(BLMFL_RESULT, input_data VARIADIC BYTEA[]) RETURNS BOOLEAN
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION blmfl_sfunc(INTERNAL, input_data VARIADIC BYTEA[]) RETURNS INTERNAL
AS 'MODULE_PATHNAME'
LANGUAGE C;

CREATE OR REPLACE FUNCTION blmfl_ffunc(INTERNAL) RETURNS BLMFL_RESULT
AS 'MODULE_PATHNAME'
LANGUAGE C;

CREATE OR REPLACE AGGREGATE blmfl(input_data VARIADIC BYTEA[]) (
    SFUNC = blmfl_sfunc,
    STYPE = INTERNAL,
    FINALFUNC = blmfl_ffunc
);

-- This function suggests a value for `k`; it does not return the actual value of `k` used. 
CREATE OR REPLACE FUNCTION blmfl_optimal_k(m INT, n INT) RETURNS INT 
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION blmfl_approx_unique_count(BLMFL_RESULT) RETURNS INT 
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION blmfl_fpr(BLMFL_RESULT) RETURNS FLOAT
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION blmfl_merge(BLMFL_RESULT, BLMFL_RESULT) RETURNS BLMFL_RESULT
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE AGGREGATE blmfl_agg(BLMFL_RESULT) (
    SFUNC = BLMFL_MERGE,
    COMBINEFUNC = BLMFL_MERGE,
    STYPE = BLMFL_RESULT,
    PARALLEL = SAFE
);

-- Trying VARIADIC
CREATE OR REPLACE FUNCTION blmfl_test_any(BLMFL_RESULT, input_data VARIADIC "any") RETURNS BOOLEAN
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION blmfl_sfunc_any(INTERNAL, VARIADIC "any") RETURNS INTERNAL
AS 'MODULE_PATHNAME'
LANGUAGE C;

CREATE OR REPLACE FUNCTION blmfl_ffunc_any(INTERNAL) RETURNS BLMFL_RESULT
AS 'MODULE_PATHNAME'
LANGUAGE C;

CREATE OR REPLACE AGGREGATE blmfl_any(VARIADIC "any") (
    SFUNC = blmfl_sfunc_any,
    STYPE = INTERNAL,
    FINALFUNC = blmfl_ffunc_any
);


-- iid functions
CREATE OR REPLACE FUNCTION is_iid_ge(record, record, boolean[])
RETURNS boolean
AS 'MODULE_PATHNAME', 'is_iid_ge'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION is_iid_le(record, record, boolean[])
RETURNS boolean
AS 'MODULE_PATHNAME', 'is_iid_le'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION is_iid_greater(record, record, boolean[])
RETURNS boolean
AS 'MODULE_PATHNAME', 'is_iid_greater'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION is_iid_less(record, record, boolean[])
RETURNS boolean
AS 'MODULE_PATHNAME', 'is_iid_less'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION is_iid_equal(record, record)
RETURNS boolean
AS 'MODULE_PATHNAME', 'is_iid_equal'
LANGUAGE C IMMUTABLE STRICT;



-- Miscellaneous
/*
i-Rex's internal id
*/

CREATE OR REPLACE FUNCTION GREATER_IID(ANYELEMENT, ANYELEMENT)
RETURNS ANYELEMENT IMMUTABLE LEAKPROOF LANGUAGE SQL AS $$
SELECT
    CASE
        WHEN $1 IS NULL THEN $2 -- needed for the very first transition from NULL initial value
        ELSE (CASE WHEN $1 < $2 THEN $2 ELSE $1 END)
    END
$$;
CREATE OR REPLACE AGGREGATE MAX_IID(ANYELEMENT) (
    SFUNC = GREATER_IID,
    COMBINEFUNC = GREATER_IID,
    STYPE = ANYELEMENT,
    PARALLEL = SAFE
);

CREATE OR REPLACE FUNCTION LESSER_IID(ANYELEMENT, ANYELEMENT)
RETURNS ANYELEMENT IMMUTABLE LEAKPROOF LANGUAGE SQL AS $$
SELECT
    CASE
        WHEN $1 IS NULL THEN $2 -- needed for the very first transition from NULL initial value
        ELSE (CASE WHEN $1 > $2 THEN $2 ELSE $1 END)
    END
$$;
CREATE OR REPLACE AGGREGATE MIN_IID(ANYELEMENT) (
    SFUNC = LESSER_IID,
    COMBINEFUNC = LESSER_IID,
    STYPE = ANYELEMENT,
    PARALLEL = SAFE
);

/*
sargable summaries
*/

CREATE OR REPLACE FUNCTION SARG_SFUNC(ANYARRAY, ANYNONARRAY)
RETURNS ANYARRAY IMMUTABLE LEAKPROOF LANGUAGE SQL AS $$
SELECT ARRAY[LEAST($1[1], $2), GREATEST($1[2], $2)]
$$;

CREATE OR REPLACE FUNCTION SARG_CFUNC(ANYARRAY, ANYARRAY)
RETURNS ANYARRAY IMMUTABLE LEAKPROOF LANGUAGE SQL AS $$
SELECT ARRAY[LEAST($1[1], $2[1]), GREATEST($1[2], $2[2])]
$$;

CREATE OR REPLACE AGGREGATE SARG_AGG(ANYNONARRAY) (
    SFUNC = SARG_SFUNC,
    COMBINEFUNC = SARG_CFUNC,
    STYPE = ANYARRAY,
    INITCOND = '{NULL, NULL}',
    PARALLEL = SAFE
);

CREATE OR REPLACE AGGREGATE SARG_AGG(ANYARRAY) (
    SFUNC = SARG_CFUNC,
    COMBINEFUNC = SARG_CFUNC,
    STYPE = ANYARRAY,
    INITCOND = '{NULL, NULL}',
    PARALLEL = SAFE
);
