server {
    listen 80;
    server_name $host;
    root /var/www/html/;

    # proxy pass authorized requests to your service
    location /api {
        # forward authorized requests to your service 
        include uwsgi_params;
	    uwsgi_pass backend:8080;
	    uwsgi_temp_file_write_size 64k;
        uwsgi_connect_timeout 10080s;
        uwsgi_send_timeout 10080;
        uwsgi_read_timeout 10080;
        uwsgi_buffer_size 64k;
        uwsgi_buffers 16 32k;
        uwsgi_busy_buffers_size 64k;
        uwsgi_request_buffering off;
        uwsgi_buffering off;
    }

	location / {
        # serve the irex vue app if authenticated
   	    root /usr/share/nginx/html;
        # try_files $uri $uri/ /index.html;
        index index.html index.htm;
    }
}
